apiVersion: v1
kind: Service
metadata:
  name: test-loadbalancer-service-frontend
  labels:
    app: test-loadbalancer-service-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: test-service-frontend
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-frontend
  labels:
    app: test-service-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-service-frontend
    spec:
      containers:
        - name: test-service-frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          image: asia.gcr.io/tokyo-eye-313109/test-service-frontend:0.1.0
  selector:
    matchLabels:
      app: test-service-frontend
