export const GENERATE_TESTS = 'GENERATE_TESTS';
export const CREATE_ATTEMPTS = 'CREATE_ATTEMPTS';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const FETCH_TEST_DETAIL = 'FETCH_TEST_DETAIL';
export const RESET_STATE = 'RESET_STATE';